 ￼
name: Works at all second edition

on: [push]

jobs:
  my-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 2
        run: |
          echo Hello World 2
